package lk.directpay.task.enums;

public enum ActivityLogAction {
    SIGN_UP("Sign up"),
    LOGIN("Login"),
    SEND_OTP("Send OTP"),
    VERIFY_OTP("Verify OTP"),
    SEND_SMS("Send SMS"),
    UPLOAD_RESOURCES("Upload Resources"),
    DEVICE_VERIFY("Device Verify"),
    VALIDATE_USER_DETAILS("Validate User details"),
    LOGIN_SWITCH("Login Switch"),
    CHANGE_PIN("Change PIN"),
    GET_REFRESH_TOKEN("Get refresh token"),
    LOGIN_INIT("Login init"),
    LOAD_DEVICE_LIST("Load Device list"),
    GET_SIGNUP_GUIDE("Get Signup Guide"),
    CHECK_UPDATES("Check updates"),
    GET_CITY_LIST("Get City List"),
    GET_TERMS_AND_CONDITIONS("Get Terms and Conditions"),
    GET_CONTACT_INFO("Get Contact Info"),
    GET_BANNERS("Get banners"),
    GET_ALL_BANKS("Get all banks"),
    GET_CEFT_BANKS("Get Ceft banks"),
    GET_CREDIT_CARD_ENABLED_BANKS("Get Credit card enabled banks"),
    GET_SLIPS_ENABLED_BANK_BRANCHES("Get Credit card enabled bank branches"),
    FUND_TRANSFER("Fund Transfer"),
    NSB_TO_NSB_FUND_TRANSFER("Nsb to Nsb Fund Transfer"),
    NSB_TO_OTHER_FUND_TRANSFER("Nsb to Other Fund Transfer"),
    NSB_TO_NSB_FUND_TRANSFER_REVERSAL("Nsb to Nsb Fund Transfer Reversal"),
    NSB_COLLECTION_ACCOUNT_TO_CREDIT_CARD_TRANSFER("Nsb collection account to credit card Fund Transfer"),
    CARD_PAYMENT("Card Payment"),
    TRANSACTIONS_LIST("Transactions list"),
    CHANGE_PAYMENT_STATUS("Change Payment Status"),
    TRIPLE_DS_CALLBACK("Transactions list"),
    ALL_MESSAGES("All messages"),
    SUBJECTS("Subjects"),
    VERIFY("Verify"),
    ADD_ACCOUNT("Add Account"),
    GET_BILLER("Get Biller"),
    GET_LOCATIONS_LIST("Get locations list"),
    BILLERS_RECENT_TRANS_ACCOUNT("Billers account Recent Transactions"),
    BILLERS_CARD_RECENT_TRANS("Billers Card Recent Transactions"),
    FREQUENTLY_SAVED_BILLERS("Frequently saved billers"),
    VERIFY_ACCOUNT("Verify Account"),
    BILLER_PAYMENT("Biller Payment"),
    BILLER_LIST("Biller List"),
    ACCOUNT_LIST("Account List"),
    PAYMENT_METHOD_LIST("Payment Method List"),
    CARD_LIST("Card List"),
    ACCOUNT_AND_CARDS_LIST("Accounts and Cards list"),
    LINK_ACCOUNTS_TO_DEVICE("Link accounts to Device"),
    PAYEE_SAVE("Payee save"),
    ACCOUNT_STATEMENT("Account statement"),
    ACCOUNT_STATEMENT_PDF("Account statement PDF"),
    ACCOUNT_TRANSACTIONS("Account Transactions"),
    ACCOUNT_BALANCE("Account Balance"),
    SAVE_BILLER("Save Biller"),
    SAVED_BILLER_LIST("Saved Biller list"),
    SAVE_BENEFICIARY("Save Beneficiary"),
    PAYEE_CHANGE_STATUS("Payee change status"),
    ACCOUNT_DELETE("Account Delete"),
    CHANGE_NIC_IMAGES("Change NIC images"),
    NIC_VERIFY("NIC verify"),
    DEVICE_NICKNAME("Device nickname"),
    CHANGE_PROFILE_IMAGE("Change profile image"),
    CHANGE_MOBILE("Change mobile"),
    GET_BILLER_FOR_TRANSACTION("Get biller for transaction"),
    ADD_ACCOUNT_SIGNATURE("Add Account Signature"),
    REPORT_LOST_STOLEN_CARD("Report Lost/Stolen credit card"),
    BILL_PAYMENT_BY_ACCOUNT("Bill Payment by Account"),
    BILL_PAYMENT_BY_CARD("Bill Payment by Card"),
    REPORT_ISSUE("Report Issue"),
    SEND_MESSAGE("Send Message"),
    ALL_NOTIFICATIONS("All Notifications"),
    SEND_NOTIFICATION("Send Notification"),
    PROMOTION_CATEGORIES("Promotion Categories"),
    ALL_PROMOTIONS("Promotions"),
    STANDING_ORDERS_LIST("Standing orders list"),
    STANDING_ORDERS_DELETE("Standing orders delete"),

    UTILITY_PAYMENT("Utility payment"),
    JUSTPAY_MANDATE("Justpay mandate"),
    JUSTPAY_CHALLANGE("Justpay challange"),
    JUSTPAY_ACCOUNT_VERIFY("Justpay account verify"),
    JUSTPAY_REGISTER("Justpay register"),
    JUSTPAY_ACCOUNT_TRANSFER("Justpay Account Transfer"),
    JUSTPAY_INIT_TRAN("Justpay init tran"),
    JUSTPAY_REMOVE_ACCOUNT("Justpay remove account"),
    JUSTPAY_REFUND("Justpay refund"),
    JUTPAY_TRAN_STATUS("Justpay tran status"),
    INTERNAL_TRANSFER("Internal tranfer"),
    CEFT_TRANSACTION("CEFT transaction"),
    CUSTOMER_PRODUCT_BY_NIC("Customer product by nic"),
    GET_ACCOUNT_TRANSACTION("get account transaction"),
    ACCOUNT_INQUIRY("Account inquiry"),
    LOAD_CARD_STATEMENTS_LIST("Load Card Statements List"),
    LOAD_CARD_STATEMENT_DETAILS("Load Card Statement Details"),
    LOAD_CARD_STATEMENT_DETAILS_PDF("Load Card Statement Details PDF"),

    ADD_USER_CARD("Add User Card"),
    VERIFY_CARD("verify card"),
    DELETE_USER_CARD("Delete User Card"),
    GET_CARD_BALANCE("Get Card Balance"),
    GET_CARD_RECENT_TRANSACTIONS("Get Card recent transactions"),
    SAVE_CARD_BENEFICIARY("Save Card Beneficiary"),
    CARD_BENEFICIARY_CHANGE_STATUS("Card Beneficiary Change Status"),
    GET_BENEFICIARY("Get Beneficiary"),
    SAVED_CREDIT_CARDS_LIST("Get Saved Credit Cards List"),
    INITIATE_GOVERNMENT_PAYMENT("Initiate a government payment"),
    SAVED_PAYEE_LIST("Saved Payee"),
    DELETE_SAVED_PAYEE("Delete saved payee"),
    DELETE_SAVED_BILLER("Delete saved biller"),
    DELETE_SAVED_CREDIT_CARD("Delete saved credit card"),
    PAYEE_SEND_OTP("Send OTP"),

    //MPGS Actions
    CREATE_SESSION("Create MPGS card add session"),
    CHECK_3DS("Create 3DS enrollment"),
    TOKENIZE_CARD("Tokenize card"),
    DELETE_OTHER_BANK_CARD("Delete other bank card"),
    MPGS_PAY("Mpgs pay"),

    //API Service Actions
    CUSTOMER_INFORMATION_INQUIRY("Customer Information Inquiry"),
    SEARCH_CLIENT("Search Client"),
    CUSTOMER_PRODUCT_INQUIRY("Customer Product Inquiry"),
    JUSTPAY_ACCOUNT_REGISTRATION("Justpay Account Registration"),
    GET_ACCOUNT_TRANSACTIONS("Get Account Transactions"),
    GET_ACCOUNT_BALANCE("Get Account Balance"),
    GET_CARD_TOKEN("Get Card Token"),
    CARD_CHANGE_STATUS("Card change status"),
    GET_CLEAR_CARD_NUMBER("Get Clear Card Number"),
    INIT_JUSTPAY_TRANSACTION("Init JP transaction"),
    CEFT_TRANSFER("Ceft transfer"),
    INTERNAL_FUND_TRANSFER("Get Clear Card Number"),
    GET_CREDIT_CARD_BALANCE("Get Credit Card Balance"),
    GET_CLIENT_CARDS("Get Client Cards"),
    GET_CLIENT_INFORMATION("Get Client Information"),
    CARD_BILL_PAYMENT("Card Bill Payment"),
    VALIDATE_CONSUMER_NO("Validate Consumer Number"),
    CREATE_JUSTPAY_CHALLENGE("Create Justpay Challenge"),
    JUSTPAY_SUBMIT_DIGITAL_MANDATE("Justpay Submit Digital Mandate"),
    JUSTPAY_REVERSAL("Justpay Reversal"),
    INTERNAL_REVERSAL("internal Reversal"),
    JUSTPAY_TRANSACTION("Justpay Transaction"),
    JUSTPAY_REVERSAL_TRANSACTION("Justpay Reversal Transaction"),
    LANKA_QR_TRANSACTION("Justpay Transaction"),
    DO_UTILITY_PAYMENT("Do Utility Payment"),
    INIT_LPOPP_TRANSACTION("Init Lpopp Transactions"),
    LPOPP_TRANSACTION_REPRINT_RECEIPT("Lpopp Transaction reprint receipt"),
    VERIFY_JUSTPAY_REGISTRATION("Verify Justpay Registration");

    private final String activityLogAction;

    ActivityLogAction(String activityLogAction) {
        this.activityLogAction = activityLogAction;
    }

    public String getActivityLogAction() {
        return activityLogAction;
    }
}
